modLoader="javafml"
loaderVersion="[49,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/addavriance/terramath/issues"

[[mods]]
modId="terramath"
version="${version}"

displayName="TerraMath"
displayURL="https://modrinth.com/mod/terra-math"

logoFile="icon.png"
authors="addavriance"

description='''
Generate your Minecraft worlds using mathematical formulas! Create unique terrains from waves to spirals with custom equations.
'''

[[dependencies.terramath]]
modId="forge"
mandatory=true
versionRange="[49,)"
ordering="NONE"
side="BOTH"

[[dependencies.terramath]]
modId="minecraft"
mandatory=true
versionRange="[1.20.3,1.20.5)"
ordering="NONE"
side="BOTH"

[[dependencies.terramath]]
modId="architectury"
mandatory=true
versionRange="[10.0.8,)"
ordering="NONE"
side="BOTH"

[modproperties.terramath]
catalogueItemIcon="minecraft:repeating_command_block"